"""Compare all five taught updates on the exact degree-10 part-g Lasso problem.

Course basis: Project 1g; Lecturebook 3.9 and 4.6, 4.9--4.11; week37
Exercise 6 and week38 Exercises 1--3. The update classes are reused unchanged.
The fixed grid and training-only selection rule below were specified before
running this supplement. Test MSE is evaluated only after selecting a rate.

LLM-assisted: generated by OpenAI Codex on 5 October 2026, including the
experiment design implementation and result checks. Student review is not
asserted. This script writes results/lasso_course_comparison.json.
"""

import json
from pathlib import Path
from time import perf_counter

import numpy as np

from optimizers import OPTIMIZERS, cost_lasso, grad_lasso, grad_ols, hessian
from regression import Scaler, lasso_sklearn_parameters, mse, polynomial_features
from settings import main_split, save_results

DEGREE = 10
LAM = 1e-3
N_ITER = 40_000
TAIL = 200
# Seven logarithmically spaced rates, augmented with the smooth-part 1/L.
BASE_RATES = np.logspace(-4, -1, 7)
METHODS = ("gd", "momentum", "adagrad", "rmsprop", "adam")


def kkt_residual(theta, X, y, lam):
    """Return max Lasso KKT violation, keeping exact zero and nonzero cases.

    Course: Lecturebook 3.9, the subgradient stationarity condition. For a
    nonzero coordinate require g_j + lam*sign(theta_j)=0; for a zero one
    require |g_j|<=lam. This is a residual, not a coefficient-error bound.
    LLM-assisted: generated by OpenAI Codex, 5 October 2026.
    """
    smooth = grad_ols(theta, X, y)
    violation = np.where(theta == 0,
                         np.maximum(np.abs(smooth) - lam, 0.0),
                         np.abs(smooth + lam * np.sign(theta)))
    return float(np.max(violation))


def run_candidate(method, eta, X, y, reference, reference_cost):
    """Run 40,000 updates; score mean objective gap over the final 200.

    Course: week37 Exercise 6 / week38 Exercises 1--3 update comparisons,
    extended to the Project 1g sign(0)=0 Lasso subgradient. No test data
    enters this function. All methods start at zero with cleared state.
    The returned coefficients are the last iterate, not a tail average.
    LLM-assisted: generated by OpenAI Codex, 5 October 2026.
    """
    optimizer = OPTIMIZERS[method](float(eta))
    theta = np.zeros(X.shape[1])
    optimizer.reset(len(theta))
    tail_gaps = np.empty(TAIL)
    start = perf_counter()
    for k in range(N_ITER):
        gradient = grad_lasso(theta, X, y, LAM)
        theta -= optimizer.update(gradient, float(eta))
        if k >= N_ITER - TAIL:
            tail_gaps[k - (N_ITER - TAIL)] = float(cost_lasso(theta, X, y, LAM)) - reference_cost
    elapsed = perf_counter() - start
    if not np.all(np.isfinite(theta)) or not np.all(np.isfinite(tail_gaps)):
        raise FloatingPointError(f"Non-finite run: {method}, eta={eta}")
    # A materially negative gap would mean the purported reference is inadequate.
    if float(np.min(tail_gaps)) < -1e-10:
        raise AssertionError("Reference objective exceeded by more than roundoff.")
    return {
        "eta": float(eta),
        "iterations": N_ITER,
        "selection_mean_tail_gap": float(np.mean(tail_gaps)),
        "tail_gap_min": float(np.min(tail_gaps)),
        "tail_gap_max": float(np.max(tail_gaps)),
        "final_objective_gap": float(tail_gaps[-1]),
        "relative_coefficient_error": float(np.linalg.norm(theta - reference) / np.linalg.norm(reference)),
        "max_abs_coefficient_error": float(np.max(np.abs(theta - reference))),
        "kkt_residual": kkt_residual(theta, X, y, LAM),
        "exact_zeros": int(np.sum(theta == 0)),
        "elapsed_seconds": float(elapsed),
        "theta": theta.tolist(),
    }


def main():
    """Build the part-g problem, verify the reference, select and evaluate.

    Course: training-only scaling from Lecturebook 3.13 / week37 Exercise 1;
    mean-loss normalization and alpha=lam/2 from Lecturebook 3.14. The fixed
    optimization experiment selects on training objective, not test risk.
    LLM-assisted: generated by OpenAI Codex, 5 October 2026.
    """
    x_train, x_test, y_train, y_test = main_split()
    raw = polynomial_features(x_train, DEGREE)
    scaler = Scaler().fit(raw, y_train)
    X, y = scaler.transform(raw), scaler.center(y_train)
    X_test = scaler.transform(polynomial_features(x_test, DEGREE))
    reference = lasso_sklearn_parameters(X, y, LAM, max_iter=2_000_000, tol=1e-12)
    reference_cost = float(cost_lasso(reference, X, y, LAM))
    L = float(np.linalg.eigvalsh(hessian(X)).max())
    rates = np.unique(np.append(BASE_RATES, 1.0 / L))

    old_path = Path(__file__).resolve().parents[1] / "results" / "part_g.json"
    old = json.loads(old_path.read_text(encoding="utf-8"))
    # Codex cleanup: the same reference is now stored without the unused convergence experiment.
    ref_difference = float(np.max(np.abs(reference - np.asarray(old["reference_lasso_theta"]))))
    ref_kkt = kkt_residual(reference, X, y, LAM)
    assert ref_difference < 1e-10, "Reference differs from the existing part-g experiment."
    assert ref_kkt < 1e-9, "Coordinate-descent reference fails the KKT check."
    assert np.isclose(L, old["setup"]["lipschitz_L"], rtol=1e-12)
    direct_cost = np.mean((X @ reference - y)**2) + LAM * np.abs(reference).sum()
    assert np.isclose(reference_cost, direct_cost, rtol=1e-14, atol=1e-15)

    results = {
        "setup": {
            "degree": DEGREE, "lambda": LAM, "n_train": len(y),
            "n_test": len(y_test), "seed_and_split": "settings.main_split defaults: seed2026, n100, sigma0.1, test fraction0.2",
            "iterations_per_candidate": N_ITER, "initial_theta": "zero",
            "subgradient_at_zero": 0.0, "lipschitz_L": L,
            "base_rates": BASE_RATES.tolist(), "actual_rates": rates.tolist(),
            "selection_rule": "minimum mean training objective gap over final200 updates; exact ties choose lower eta",
            "selection_tail_updates": TAIL,
            "reported_theta": "last iterate of selected run, not an averaged iterate",
            "optimizer_defaults": "momentum0.9; RMSprop rho0.99; Adam beta1=0.9 beta2=0.999; epsilon1e-8 outside sqrt",
            "scope": "one data split, one degree/lambda, eight rates, fixed40000 update budget; no convergence guarantee or universal ranking",
            "timing_scope": "one sequential run per candidate; includes updates and200 final objective evaluations; excludes scaling, reference fit and final diagnostics; timings are descriptive",
        },
        "reference": {
            "solver": "sklearn Lasso alpha=lambda/2, fit_intercept=False, tol1e-12, max_iter2000000",
            "objective": reference_cost, "theta": reference.tolist(),
            "exact_zeros": int(np.sum(reference == 0)), "kkt_residual": ref_kkt,
            "max_abs_difference_from_saved_part_g": ref_difference,
            "test_mse": float(mse(y_test, scaler.y_mean + X_test @ reference)),
        },
        "candidates": {}, "selected": {},
    }
    for method in METHODS:
        rows = [run_candidate(method, eta, X, y, reference, reference_cost) for eta in rates]
        best = min(rows, key=lambda row: (row["selection_mean_tail_gap"], row["eta"]))
        selected = dict(best)
        theta = np.asarray(selected["theta"])
        selected["test_mse"] = float(mse(y_test, scaler.y_mean + X_test @ theta))
        results["candidates"][method] = rows
        results["selected"][method] = selected
        print(method, {key: selected[key] for key in ("eta", "selection_mean_tail_gap", "final_objective_gap",
              "relative_coefficient_error", "kkt_residual", "exact_zeros", "test_mse", "elapsed_seconds")}, flush=True)
    path = save_results("lasso_course_comparison", results)
    print("Saved", path)
    print("Reference KKT", ref_kkt, "saved-reference difference", ref_difference)


if __name__ == "__main__":
    main()
