"""Check sensitivity of the selected Lasso models to the solver tolerance.

This supplements part i without changing its archived grids or figures. It
repeats the original warm-start path for the selected degrees, then refines
the selected lambda. Both CV folds and the final refit are checked. This is
not a new search over the whole model grid.

LLM-assisted: Codex generated this script on 5 October 2026 and executed it
as part of the report audit. The student should review and understand it.
"""

import json
import warnings
from pathlib import Path

import numpy as np
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import lasso_path
from sklearn.model_selection import KFold

from regression import Scaler, make_data, polynomial_features
from settings import N_POINTS, SEED, save_results


def optimality_residual(X, y, theta, lam):
    """Maximum violation of the normalized Lasso KKT conditions.

    LLM-assisted: generated by Codex for this verification experiment.
    """
    correlation = 2 * X.T @ (y - X @ theta) / len(y)
    active = theta != 0
    residual = np.maximum(np.abs(correlation) - lam, 0)
    residual[active] = np.abs(correlation[active] - lam * np.sign(theta[active]))
    return float(np.max(residual, initial=0))


def check_fit(x_train, y_train, x_eval, y_eval, degree, lam, lam_grid):
    """Repeat one path and refine one selected penalty on the same data.

    LLM-assisted: generated by Codex; scalers are fit on training data only.
    """
    scaler = Scaler().fit(polynomial_features(x_train, degree), y_train)
    X = np.asfortranarray(scaler.transform(polynomial_features(x_train, degree)))
    yc = scaler.center(y_train)
    selected = int(np.argmin(np.abs(lam_grid - lam)))
    with warnings.catch_warnings(record=True) as recorded:
        warnings.simplefilter("always", ConvergenceWarning)
        _, path, gaps, iterations = lasso_path(
            X, yc, alphas=lam_grid / 2, max_iter=100_000, tol=1e-6,
            return_n_iter=True,
        )
        old = path[:, selected].copy()
        _, refined, refined_gaps, refined_iterations = lasso_path(
            X, yc, alphas=np.array([lam / 2]), coef_init=old.copy(),
            max_iter=2_000_000, tol=1e-10, return_n_iter=True,
        )
    new = refined[:, 0]
    Xe = scaler.transform(polynomial_features(x_eval, degree))
    old_prediction = scaler.y_mean + Xe @ old
    new_prediction = scaler.y_mean + Xe @ new
    return {
        "old_iterations": int(iterations[selected]),
        "additional_refinement_iterations": int(refined_iterations[0]),
        "old_dual_gap": float(gaps[selected]),
        "refined_dual_gap": float(refined_gaps[0]),
        "old_kkt_residual": optimality_residual(X, yc, old, lam),
        "refined_kkt_residual": optimality_residual(X, yc, new, lam),
        "old_eval_mse": float(np.mean((y_eval - old_prediction) ** 2)),
        "refined_eval_mse": float(np.mean((y_eval - new_prediction) ** 2)),
        "max_abs_prediction_change": float(np.max(np.abs(new_prediction - old_prediction))),
        "old_nonzero": int(np.count_nonzero(old)),
        "refined_nonzero": int(np.count_nonzero(new)),
        "warning_count_for_entire_path_and_refinement": len(recorded),
    }


def main():
    """Check the two reported Lasso selections at both noise levels.

    LLM-assisted: generated by Codex; uses archived selections, not new tuning.
    """
    archived = json.loads((Path(__file__).resolve().parents[1] / "results" / "part_i.json").read_text())
    lam_grid = np.array(archived["grids"]["lambda_lasso"])
    output = {"purpose": "Solver sensitivity of the previously selected models; not a full grid rerun",
              "old_settings": {"max_iter": 100_000, "tol": 1e-6},
              "refinement_settings": {"additional_max_iter": 2_000_000, "tol": 1e-10},
              "models": []}
    for sigma in (0.1, 0.3):
        x, y = make_data(N_POINTS, sigma, SEED)
        x_new, y_new = make_data(2000, sigma, SEED + 1)
        folds = list(KFold(n_splits=10, shuffle=True, random_state=SEED).split(x))
        for rule in ("min", "one_se"):
            row = archived[f"sigma={sigma}"]["k10"]["Lasso"][rule]
            degree, lam = row["degree"], row["lambda"]
            checks = [check_fit(x[tr], y[tr], x[va], y[va], degree, lam, lam_grid)
                      for tr, va in folds]
            refit = check_fit(x, y, x_new, y_new, degree, lam, lam_grid)
            old_mean = float(np.mean([c["old_eval_mse"] for c in checks]))
            new_mean = float(np.mean([c["refined_eval_mse"] for c in checks]))
            summary = {"sigma": sigma, "rule": rule, "degree": degree, "lambda": lam,
                       "archived_cv_mse": row["cv_mse"],
                       "recomputed_original_cv_mse": old_mean, "refined_cv_mse": new_mean,
                       "relative_cv_change": (new_mean - old_mean) / old_mean,
                       "max_refined_kkt_residual": max(c["refined_kkt_residual"] for c in checks + [refit]),
                       "folds": checks, "refit_on_all_100": refit}
            output["models"].append(summary)
            print(f"sigma={sigma} {rule} p={degree} lambda={lam:g}: CV {old_mean:.8f} -> {new_mean:.8f}; "
                  f"fresh test {refit['old_eval_mse']:.8f} -> {refit['refined_eval_mse']:.8f}; "
                  f"KKT={summary['max_refined_kkt_residual']:.2e}", flush=True)
    save_results("model_selection_check", output)


if __name__ == "__main__":
    main()
