"""
Basic building blocks for polynomial regression on Runge's function.

Contents
--------
- runge, make_data          : the target function and noisy data sets
- polynomial_features       : design matrix with columns x, x^2, ..., x^p
- Scaler                    : standardisation of X and centring of y (fitted on training data only)
- ols_parameters            : closed-form OLS through the SVD-based pseudoinverse
- ridge_parameters          : closed-form Ridge through the SVD (shows the shrinkage factors)
- lasso_sklearn_parameters  : reference Lasso solution from Scikit-Learn (coordinate descent)
- PolynomialRegression      : small estimator class gluing it all together; it follows the
                              Scikit-Learn estimator interface so it can be used with KFold and
                              cross_val_score
- mse, r2                   : error metrics

Conventions (used everywhere in the project)
--------------------------------------------
Cost functions are normalised with 1/n:
    OLS   : C(theta) = (1/n) ||y - X theta||^2
    Ridge : C(theta) = (1/n) ||y - X theta||^2 + lam ||theta||^2
    Lasso : C(theta) = (1/n) ||y - X theta||^2 + lam ||theta||_1
so the Ridge solution is theta = (X^T X + n lam I)^{-1} X^T y. In Scikit-Learn this corresponds
to Ridge(alpha = n*lam) and Lasso(alpha = lam/2), see the tests.

The design matrix has no column of ones. Features are standardised and y is centred using the
training data. Predictions in standardized coordinates add the training mean of y; the intercept
in the original monomial coordinates is instead y_mean - sum_j beta_j * X_mean_j. Neither is
penalised. Scaler.original_coefficients performs this conversion.

Connection to the taught methods (course-source audit by Codex, 5 October 2026)
---------------------------------------------------------------------------
- Week 35 Exercise 2 and Lecturebook Sections 3.1-3.5: construct polynomial columns, solve OLS
  with SVD/pseudoinverse, and evaluate MSE and R^2. The exercise uses a quadratic on [0, 1];
  Project 1 part a replaces that example by Runge's function on [-1, 1].
- Week 35 Tuesday Case 1 and Lecturebook Section 3.13, Eq. (3.90) (PDF pages 143-146): fit
  centering/scaling on training data, omit the constant column, and recover the intercept.
- Week 35 Tuesday Case 2 and Section 3.8: Ridge filters the singular-value directions. That
  classroom snippet uses d_j^2 + lambda with an unnormalised residual sum of squares. Here
  d_j^2 + n*lambda implements the mean-loss convention explained in Section 3.14, Eq. (3.95)
  (PDF page 149). Thus identical numerical penalties in the two conventions are not equivalent.
- Week 36 Exercise 4 and Section 3.14: PolynomialRegression packages these same steps so that
  fitting in a fold or bootstrap sample also refits its scaler; the class wrapper is an
  implementation choice, not a different regression algorithm.
Course references identify the mathematical method, not copied student exercise solutions.

LLM-assisted
------------
Code level 2. The numerical code was written by the author. The docstrings and the course
references above were written with LLM assistance (Claude via Claude Code and OpenAI Codex,
October 2026). checked_lasso_path was generated by OpenAI Codex on 5 October 2026.
Verification: every closed-form result is compared with Scikit-Learn in tests/test_regression.py.
"""

import warnings
import numpy as np
from sklearn.base import BaseEstimator, RegressorMixin
from sklearn.exceptions import ConvergenceWarning
from sklearn.linear_model import Lasso, lasso_path


# ----------------------------------------------------------------------------------------------
# Data
# ----------------------------------------------------------------------------------------------
def runge(x):
    """Runge's function f(x) = 1 / (1 + 25 x^2).

    This is the target specified in Project1.pdf, part a (PDF page 2).
    """
    return 1.0 / (1.0 + 25.0 * x**2)


def make_data(n, noise=0.1, seed=None, uniform=True):
    """Return n points (x, y) with y = f(x) + eps, eps ~ N(0, noise^2), x in [-1, 1].

    uniform=True draws x from U[-1, 1]; uniform=False uses an equidistant grid.

    Project 1 part a explicitly allows both input designs. The default experiments use random
    inputs, unlike the fixed linspace input in Week 35 Exercise 3 / Week 36 Exercise 3. A fresh
    call with a new seed therefore redraws both input locations and observation noise. This
    matters when interpreting expectations over training sets in a bias-variance experiment.
    """
    rng = np.random.default_rng(seed)
    if uniform:
        x = rng.uniform(-1.0, 1.0, n)
    else:
        x = np.linspace(-1.0, 1.0, n)
    y = runge(x) + noise * rng.standard_normal(n)
    return x, y


def polynomial_features(x, degree):
    """Design matrix with columns x^1, ..., x^degree (shape n x degree).

    The constant column is left out on purpose: we centre the data instead (see Scaler).

    Week 35 Exercise 2 writes [1, x, x^2]; Section 3.13 shows the equivalent centered form used
    here. For degree p this function returns p slope columns, not p+1 columns. Degree zero
    gives no slope columns, so PolynomialRegression predicts only the training target mean.
    """
    x = np.asarray(x, dtype=float).ravel()
    return x[:, None] ** np.arange(1, degree + 1)[None, :]


# ----------------------------------------------------------------------------------------------
# Scaling
# ----------------------------------------------------------------------------------------------
class Scaler:
    """Standardise the columns of X and centre y with statistics from the TRAINING data.

    With scale=False the columns are only centred (divided by 1), which is the minimal
    preprocessing needed to drop the intercept column.

    Following Week 35 Tuesday Case 1 / Lecturebook Section 3.13, centering handles the
    intercept, while division by feature standard deviations changes the relative scaling
    of the penalty. These are separate operations. The target is centered, not standardized.
    """

    def __init__(self, scale=True):
        """Choose between standardization (scale=True) and centering only."""
        self.scale = scale

    def fit(self, X, y):
        """Store column means, ddof=0 standard deviations, and target mean for one fit.

        Supply training rows only, including when called from resampling. The zero-standard-
        deviation guard avoids division by zero for a constant feature. This implements the
        training-only centering/scaling recipe in Section 3.13 and Week 35 Tuesday Case 1.
        """
        self.X_mean = X.mean(axis=0)
        self.X_std = X.std(axis=0) if self.scale else np.ones(X.shape[1])
        self.X_std[self.X_std == 0.0] = 1.0  # guard against constant columns
        self.y_mean = float(np.mean(y))
        return self

    def transform(self, X):
        """Apply the stored training transform without fitting new statistics.

        This is the frozen test/fold transform required by Sections 3.13-3.14. Computing the
        test set's own mean here would give it a different coordinate system and leak data.
        """
        return (X - self.X_mean) / self.X_std

    def center(self, y):
        """Subtract the fitted training target mean; do not estimate a mean from this input."""
        return y - self.y_mean

    def original_coefficients(self, theta):
        """Map parameters of the scaled problem back to y = beta_0 + sum_j beta_j x^j.

        Undo division by each feature scale, then use Eq. (3.90) of Section 3.13:
        beta_j = theta_j / s_j; beta_0 = y_mean - sum_j beta_j * X_mean_j.
        The standardized-coordinate intercept y_mean is generally not this raw beta_0.
        """
        beta = theta / self.X_std
        beta0 = self.y_mean - np.sum(beta * self.X_mean)
        return beta0, beta


# ----------------------------------------------------------------------------------------------
# Closed-form solutions (on already scaled/centred data)
# ----------------------------------------------------------------------------------------------
def ols_parameters(X, y):
    """OLS solution theta = X^+ y, with the pseudoinverse computed from the SVD of X.

    Using pinv instead of inv(X^T X) avoids squaring the condition number of X, which matters
    for high polynomial degrees where the columns x^j are almost linearly dependent.

    This is the own-OLS SVD option in Week 35 Exercise 2 and Lecturebook Section 3.3,
    Eq. (3.11). Callers supply already centered/scaled X and centered y. NumPy pinv uses a
    relative singular-value cutoff (1e-15 by default); comparison solvers must use a compatible
    cutoff. Otherwise a numerically truncated least-squares fit can act as extra regularization.
    """
    return np.linalg.pinv(X) @ y


def ridge_parameters(X, y, lam):
    """Minimiser of (1/n)||y - X theta||^2 + lam ||theta||^2.

    With X = U S V^T we get theta = V diag(s_j / (s_j^2 + n lam)) U^T y, i.e. each singular
    mode of the OLS solution is multiplied by the shrinkage factor s_j^2 / (s_j^2 + n lam).

    This follows Week 35 Tuesday Case 2, with its unnormalised lambda replaced by n*lam as
    prescribed by Section 3.14, Eq. (3.95). n is the number of rows fitted on this call, so in
    cross-validation it is the training-fold size. For the equivalent sklearn model use
    Ridge(alpha=n*lam, fit_intercept=False) on these already centered arrays.
    """
    n = X.shape[0]
    U, s, Vt = np.linalg.svd(X, full_matrices=False)
    return Vt.T @ ((s / (s**2 + n * lam)) * (U.T @ y))


def ridge_shrinkage_factors(X, lam):
    """Shrinkage factors s_j^2 / (s_j^2 + n lam) for the singular values s_j of X.

    See Section 3.8, Eq. (3.48), and its normalized-loss conversion in Section 3.14. Their sum
    counts effective slope degrees of freedom; add one for a fitted unpenalized intercept.
    """
    s = np.linalg.svd(X, compute_uv=False)
    return s**2 / (s**2 + X.shape[0] * lam)


def lasso_sklearn_parameters(X, y, lam, max_iter=200_000, tol=1e-10):
    """Reference Lasso solution from Scikit-Learn for our cost (1/n)||y-X theta||^2 + lam||theta||_1.

    Scikit-Learn minimises (1/(2n))||y - X theta||^2 + alpha ||theta||_1, which is our cost
    divided by two, hence alpha = lam / 2. X and y are already centred, so no intercept.

    This is the library reference, not our own Lasso optimizer. The convention matches the
    conversion discussed in Section 3.14 (PDF page 149); the custom subgradient
    implementations used for the optimization experiments are in optimizers.py.
    """
    model = Lasso(alpha=lam / 2.0, fit_intercept=False, max_iter=max_iter, tol=tol)
    model.fit(X, y)
    return model.coef_.copy()


def checked_lasso_path(X, y, lambdas, tol=1e-6, gap_tol=1e-7, kkt_tol=1e-7,
                       max_iter=2_000_000, refinement_iter=10_000_000):
    """Coordinate-descent path, accepting only certified Lasso solutions.

    The course uses alpha=lambda/2 (book 3.14). Check both sklearn's dual
    absolute dual gap of the library's half-loss objective, and the stationarity conditions
    of book 3.9. A failed candidate is continued from its current iterate;
    an unresolved candidate raises instead of silently entering the CV grid.
    This is a verification wrapper around the taught library reference.
    LLM-assisted: generated by Codex, 5 October 2026, to repair the full-grid
    convergence limitation.
    """
    X = np.asfortranarray(X, dtype=float)
    y = np.asarray(y, dtype=float)
    lambdas = np.asarray(lambdas, dtype=float)
    gap_scale = max(float(np.mean(y**2)), np.finfo(float).eps)
    solver_tol = min(tol, gap_tol / gap_scale)
    with warnings.catch_warnings():
        warnings.simplefilter('ignore', ConvergenceWarning)
        _, coefs, gaps, iterations = lasso_path(
            X, y, alphas=lambdas / 2, tol=solver_tol, max_iter=max_iter, return_n_iter=True)
    initial_limits = int(np.sum(np.asarray(iterations) >= max_iter))
    residuals, refined = [], 0
    for j, lam in enumerate(lambdas):
        # For nonzero slopes: g_j + lambda*sign(theta_j)=0; at zero: |g_j|<=lambda.
        smooth = 2 * X.T @ (X @ coefs[:, j] - y) / len(y)
        residual = np.where(coefs[:, j] == 0, np.maximum(np.abs(smooth) - lam, 0),
                            np.abs(smooth + lam * np.sign(coefs[:, j])))
        violation = float(np.max(residual, initial=0))
        if abs(gaps[j]) > gap_tol or violation > kkt_tol:
            refined += 1
            with warnings.catch_warnings():
                warnings.simplefilter('ignore', ConvergenceWarning)
                _, theta, gap, extra = lasso_path(
                    X, y, alphas=np.array([lam / 2]), coef_init=coefs[:, j].copy(),
                    tol=min(solver_tol, 1e-10), max_iter=refinement_iter, return_n_iter=True)
            coefs[:, j], gaps[j] = theta[:, 0], gap[0]
            iterations[j] += extra[0]
            smooth = 2 * X.T @ (X @ coefs[:, j] - y) / len(y)
            residual = np.where(coefs[:, j] == 0, np.maximum(np.abs(smooth) - lam, 0),
                                np.abs(smooth + lam * np.sign(coefs[:, j])))
            violation = float(np.max(residual, initial=0))
        if not np.isfinite(violation) or not np.isfinite(gaps[j]) or abs(gaps[j]) > gap_tol or violation > kkt_tol:
            raise RuntimeError(f'Unconverged Lasso candidate: lambda={lam:g}, gap={gaps[j]:.3g}, KKT={violation:.3g}')
        residuals.append(violation)
    return coefs, {'total': len(lambdas), 'unresolved': 0, 'initial_hit_limit': initial_limits,
                   'refined': refined, 'max_dual_gap': float(np.max(np.abs(gaps))),
                   'max_kkt_residual': max(residuals), 'max_sweeps': int(max(iterations)),
                   'requested_solver_tol': tol, 'dual_gap_tolerance': gap_tol, 'kkt_tolerance': kkt_tol}


# ----------------------------------------------------------------------------------------------
# Metrics
# ----------------------------------------------------------------------------------------------
def mse(y, y_pred):
    """Mean squared error.

    Implements Week 35 Exercise 2 item 3 / Lecturebook Eq. (3.17). The denominator is the
    number of evaluated observations, which can differ from the number used in fitting.
    """
    y, y_pred = np.asarray(y).ravel(), np.asarray(y_pred).ravel()
    return np.mean((y - y_pred) ** 2)


def r2(y, y_pred):
    """Coefficient of determination R^2.

    Implements Week 35 Exercise 2 item 3 / Lecturebook Eq. (3.18). Its baseline is the mean
    of the evaluation targets, not the stored training mean. Negative scores are possible;
    the present formula assumes nonconstant evaluation targets (as in these experiments).
    """
    y, y_pred = np.asarray(y).ravel(), np.asarray(y_pred).ravel()
    return 1.0 - np.sum((y - y_pred) ** 2) / np.sum((y - np.mean(y)) ** 2)


# ----------------------------------------------------------------------------------------------
# Estimator
# ----------------------------------------------------------------------------------------------
class PolynomialRegression(BaseEstimator, RegressorMixin):
    """Polynomial regression in x with OLS, Ridge or Lasso and built-in train-only scaling.

    Parameters
    ----------
    degree : int
        Polynomial degree p (the model has p slope parameters plus an unpenalised intercept).
    method : {"ols", "ridge", "lasso"}
    lam : float
        Penalty lambda in the 1/n-normalised cost (ignored for OLS).
    scale : bool
        Standardise the columns (True) or only centre them (False).
    solver : callable or None
        Optional function solver(X, y, lam) -> theta on the scaled data. Used to plug in our own
        gradient-descent Lasso; the default for Lasso is Scikit-Learn's coordinate descent.

    Because it follows the Scikit-Learn interface (fit/predict/get_params), it can be passed
    directly to cross_val_score, and the scaling is then refitted inside every training fold.

    The mathematical steps are the course's polynomial feature construction, training-only
    scaling, and regression fit. Encapsulating them in an estimator has the same purpose as
    the PolynomialFeatures -> StandardScaler -> regression pipeline in Section 3.14: no
    learned preprocessing is shared between training folds and their held-out observations.
    """

    def __init__(self, degree=5, method="ols", lam=0.0, scale=True, solver=None):
        """Store the hyperparameters (scikit-learn estimator convention)."""
        self.degree = degree
        self.method = method
        self.lam = lam
        self.scale = scale
        self.solver = solver

    def fit(self, x, y):
        """Fit features, scaler and chosen solver using only the observations passed here.

        A resampling caller passes only its current training rows. Recreating Scaler on every
        call follows Section 3.14 / Week 36 Exercise 4, including refitting the intercept.
        """
        X = polynomial_features(x, self.degree)
        self.scaler_ = Scaler(self.scale).fit(X, y)
        Xs = self.scaler_.transform(X)
        yc = self.scaler_.center(np.asarray(y, dtype=float).ravel())
        if self.solver is not None:
            self.theta_ = self.solver(Xs, yc, self.lam)
        elif self.method == "ols":
            self.theta_ = ols_parameters(Xs, yc)
        elif self.method == "ridge":
            self.theta_ = ridge_parameters(Xs, yc, self.lam)
        elif self.method == "lasso":
            self.theta_ = lasso_sklearn_parameters(Xs, yc, self.lam)
        else:
            raise ValueError(f"unknown method {self.method!r}")
        self.intercept_ = self.scaler_.y_mean
        return self

    def predict(self, x):
        """Predict with the training scaler and the fitted coefficients."""
        Xs = self.scaler_.transform(polynomial_features(x, self.degree))
        return self.intercept_ + Xs @ self.theta_
