"""Part b, continued: the Ridge figure of the report and paired OLS/Ridge comparisons.

LLM-assisted (code level 4): generated by OpenAI Codex, 5 October 2026. This script adds
train/test errors, coefficient norms, and a paired simulation across
sample sizes and noise levels. The four positive penalties are fixed before
the simulation; test data are used only to describe their performance.
Run: python ridge_supplement.py
"""

import json

import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from sklearn.model_selection import train_test_split

from regression import Scaler, main_split, make_data, polynomial_features
from plot_style import (DOUBLE, METHOD_COLORS, RESULTS_DIR, ordered_colors, save, save_results,
                        set_style)


DEGREES = np.arange(1, 21)
PENALTIES = np.array([0.0, 1e-7, 1e-5, 1e-3, 1e-1])
LABELS = ["OLS", r"Ridge $10^{-7}$", r"Ridge $10^{-5}$",
          r"Ridge $10^{-3}$", r"Ridge $10^{-1}$"]
REPETITIONS = 40
SEED_BASE = 5_100_000


def fit_path(x_train, y_train, x_test, degree, penalties):
    """Use one SVD for a fixed degree; OLS matches NumPy's pinv cutoff.

    LLM-assisted: generated by OpenAI Codex on 5 October 2026
    for the supplemental experiments described in the module docstring.
    """
    X = polynomial_features(x_train, degree)
    scaler = Scaler().fit(X, y_train)
    Z, yc = scaler.transform(X), scaler.center(y_train)
    U, s, Vt = np.linalg.svd(Z, full_matrices=False)
    filters = s[:, None] / (s[:, None] ** 2 + len(y_train) * penalties[None, :])
    if penalties[0] == 0.0:
        filters[:, 0] = np.where(s > 1e-15 * s.max(), 1.0 / s, 0.0)
    theta = Vt.T @ (filters * (U.T @ yc)[:, None])
    return (scaler.y_mean + Z @ theta,
            scaler.y_mean + scaler.transform(polynomial_features(x_test, degree)) @ theta,
            theta.T)


def summarize(values):
    """Axis 0 is independent datasets, remaining axes are degree and method.

    LLM-assisted: generated by OpenAI Codex on 5 October 2026
    for the supplemental experiments described in the module docstring.
    """
    return {"mean": values.mean(axis=0), "median": np.median(values, axis=0),
            "q1": np.quantile(values, 0.25, axis=0),
            "q3": np.quantile(values, 0.75, axis=0),
            "mc_se_mean": values.std(axis=0, ddof=1) / np.sqrt(len(values))}


def main():
    """LLM-assisted: generated by OpenAI Codex on 5 October 2026
    for the supplemental experiments described in the module docstring.
    """
    set_style()
    xtr, xte, ytr, yte = main_split()
    original = json.loads((RESULTS_DIR / "part_b.json").read_text(encoding="utf-8"))
    saved = original["main"]
    train_var, test_var = np.var(ytr), np.var(yte)
    metrics = {"degrees": saved["degrees"], "lambdas": saved["lambdas"],
               "mse_train": saved["train_mse"], "mse_test": saved["test_mse"],
               "r2_train": 1 - np.asarray(saved["train_mse"]) / train_var,
               "r2_test": 1 - np.asarray(saved["test_mse"]) / test_var,
               "variance_train_ddof0": train_var, "variance_test_ddof0": test_var}
    # Compute paths independently and check against the saved grid.
    grid_lambdas = np.asarray(saved["lambdas"])
    coefficient_paths, train_values, test_values = [], [], []
    for p in DEGREES:
        tr, te, theta = fit_path(xtr, ytr, xte, p, PENALTIES)
        train_values.append(np.mean((ytr[:, None] - tr) ** 2, axis=0))
        test_values.append(np.mean((yte[:, None] - te) ** 2, axis=0))
        coefficient_paths.append(theta)
    train_values, test_values = np.array(train_values), np.array(test_values)
    grid_index = [int(np.argmin(abs(grid_lambdas - lam))) for lam in PENALTIES[1:]]
    difference = max(np.max(abs(train_values[:, 1:] - np.asarray(saved["train_mse"])[:, grid_index])),
                     np.max(abs(test_values[:, 1:] - np.asarray(saved["test_mse"])[:, grid_index])))
    if difference > 1e-8:
        raise ValueError(f"Supplement differs from saved main experiment by {difference}")
    metrics.update({"selected_penalties_including_ols": PENALTIES,
                    "selected_mse_train": train_values, "selected_mse_test": test_values,
                    "selected_r2_train": 1 - train_values / train_var,
                    "selected_r2_test": 1 - test_values / test_var,
                    "selected_theta_by_degree": coefficient_paths,
                    "selected_theta_l2_norm": [np.linalg.norm(t, axis=1) for t in coefficient_paths],
                    "max_abs_recomputed_vs_saved_mse": difference})

    output = {"metadata": {"ai_assistance": "OpenAI Codex, 2026-10-05",
              "repetitions": REPETITIONS, "seed_base": SEED_BASE,
              "split_fraction_test": 0.2, "split_seed": "71 + repetition",
              "degree_grid": DEGREES, "penalties": PENALTIES,
              "selection": "Fixed illustrative penalties; no parameter selected on test outcomes.",
              "pairing": "Methods use identical data/splits within each repetition; scenarios reuse RNG seeds.",
              "uncertainty": "q1/q3 describe dataset variability; mc_se_mean is a descriptive Monte Carlo SE, not a confidence interval. Heavy tails may make 40 repeats insufficient.",
              "axis_order": "summaries: degree then method; raw test MSE: repetition, degree, method",
              "noise_free_caveat": "sigma=0 measures approximation/generalization without irreducible noise."},
              "main": metrics, "ensemble": {}}

    scenarios = [(n, 0.1) for n in (50, 100, 500, 1000)]
    scenarios += [(100, s) for s in (0.0, 0.05, 0.3)]
    for n, sigma in scenarios:
        train = np.empty((REPETITIONS, len(DEGREES), len(PENALTIES)))
        test = np.empty_like(train)
        for rep in range(REPETITIONS):
            x, y = make_data(n, sigma, seed=SEED_BASE + rep)
            xt, xv, yt, yv = train_test_split(x, y, test_size=0.2, random_state=71 + rep)
            for j, degree in enumerate(DEGREES):
                ptrain, ptest, _ = fit_path(xt, yt, xv, degree, PENALTIES)
                train[rep, j] = np.mean((yt[:, None] - ptrain) ** 2, axis=0)
                test[rep, j] = np.mean((yv[:, None] - ptest) ** 2, axis=0)
        key = f"n={n},sigma={sigma:g}"
        output["ensemble"][key] = {"n": n, "sigma": sigma, "n_train": len(xt),
                                  "n_test": len(xv), "train_mse": summarize(train),
                                  "test_mse": summarize(test), "raw_test_mse": test,
                                  "paired_test_mse_minus_ols": summarize(test - test[:, :, :1])}
        print(f"Completed {key}: {REPETITIONS} datasets", flush=True)

    # LLM-assisted (Claude Opus 5.5, 5 October 2026): the report's Ridge figure, with test MSE,
    # training MSE and coefficient norm side by side. Test R^2 = 1 - MSE/var(y) on the same split, so it
    # carries no information beyond the test MSE.
    norms = np.array([np.linalg.norm(t, axis=1) for t in coefficient_paths])
    ridge_shades = ordered_colors(len(PENALTIES) - 1, light=0.35, base=METHOD_COLORS["Ridge"])
    styles = [(METHOD_COLORS["OLS"], "--")] + [(c, "-") for c in ridge_shades]
    fig, axes = plt.subplots(1, 3, figsize=(DOUBLE, 2.45))
    panels = [(test_values, "Test MSE"), (train_values, "Training MSE"),
              (norms, r"$\|\theta\|_2$ (standardized features)")]
    for ax, (values, ylabel), tag in zip(axes, panels, ("(a)", "(b)", "(c)")):
        for j, label in enumerate(LABELS):
            color, ls = styles[j]
            ax.semilogy(DEGREES, values[:, j], ls, color=color, label=label)
        ax.set_xlabel("Polynomial degree $p$")
        ax.set_ylabel(ylabel)
        ax.set_xticks([1, 5, 10, 15, 20])
        ax.text(0.03, 0.96, tag, transform=ax.transAxes, va="top", fontweight="bold")
    axes[1].set_ylim(top=0.2)  # room for the panel label above the degree-1 point
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc="lower center", ncol=5, fontsize=6.5)
    fig.tight_layout(rect=(0, 0.1, 1, 1))
    save(fig, "b_ridge")

    save_results("ridge_supplement", output)
    print("Wrote ridge_supplement.json and the report figure b_ridge.pdf.", flush=True)


if __name__ == "__main__":
    main()
