"""Additional checks for project parts e and h, without changing earlier results.

LLM-assisted: generated by OpenAI Codex on 5 October 2026 to verify both
gradient sources inside Ridge GD and extend the SGD comparison to Ridge.
These are supplemental experiments, not results from the original run_all.py.
Run from any directory with: python Project1/code/verification_supplement.py
Writes only results/verification_supplement.json. Timings are local measurements.
"""

import json
from pathlib import Path
import time

import numpy as np

from optimizers import (GD, OPTIMIZERS, cost_ridge, grad_ridge, gradient_descent,
                        hessian, make_gradient, stochastic_gradient_descent)
from regression import Scaler, polynomial_features, ridge_parameters
from settings import main_split


def main():
    """LLM-assisted: generated by OpenAI Codex on 5 October 2026
    for the supplemental experiments described in the module docstring.
    """
    x_train, x_test, y_train, y_test = main_split()
    degree, lam, epochs = 6, 1e-3, 2000
    raw = polynomial_features(x_train, degree)
    scaler = Scaler().fit(raw, y_train)
    X, y = scaler.transform(raw), scaler.center(y_train)
    Xt = scaler.transform(polynomial_features(x_test, degree))
    reference = ridge_parameters(X, y, lam)
    reference_cost = float(cost_ridge(reference, X, y, lam))
    reference_prediction = scaler.y_mean + Xt @ reference
    h = np.linalg.eigvalsh(hessian(X, lam))
    eta_opt = float(2 / (h.min() + h.max()))
    out = {"provenance": "Supplemental experiment generated and executed with OpenAI Codex, 5 October 2026.",
           "setup": {"degree": degree, "lambda": lam, "n_train": len(y),
                     "epochs": epochs, "seeds": [0, 1, 2],
                     "reference_cost": reference_cost,
                     "reference_test_mse": float(np.mean((reference_prediction - y_test) ** 2)),
                     "hessian_min": float(h.min()), "hessian_max": float(h.max()),
                     "eta_opt_quadratic": eta_opt,
                     "stopping_criterion_gd": "relative parameter error < 1e-6",
                     "selection_sgd": "minimum geometric mean excess penalized training cost over final 200 epochs, seed 0",
                     "limits": "Small-grid supplement on the original 80/20 split. Test MSE is descriptive only, never used to tune. Timing includes diagnostics and is machine-dependent."}}
    theta_runs = {}
    out["ridge_gradient_sources"] = {}
    for label, auto in (("analytic", False), ("autograd", True)):
        start = time.perf_counter()
        theta, info = gradient_descent(make_gradient("ridge", X, y, lam, use_autograd=auto),
                                       np.zeros(degree), GD(eta_opt), 20000,
                                       theta_ref=reference, tol=1e-6)
        theta_runs[label] = theta
        out["ridge_gradient_sources"][label] = {
            "iterations": info["iterations"], "converged": info["converged"],
            "final_relative_error": float(info["errors"][-1]),
            "time_s": time.perf_counter() - start}
    out["ridge_gradient_sources"]["max_abs_parameter_difference"] = float(
        np.max(np.abs(theta_runs["analytic"] - theta_runs["autograd"])))
    assert all(out["ridge_gradient_sources"][name]["converged"] for name in theta_runs)
    assert np.allclose(theta_runs["analytic"], theta_runs["autograd"], rtol=0, atol=1e-11)

    def run(name, eta, batch, seed, decay=False, run_epochs=epochs):
        """LLM-assisted: generated by OpenAI Codex on 5 October 2026
        for the supplemental experiments described in the module docstring.
        """
        updates_per_epoch = int(np.ceil(len(y) / batch))
        t1 = 250 * updates_per_epoch
        schedule = (lambda t: eta * t1 / (t + t1)) if decay else None
        start = time.perf_counter()
        with np.errstate(over="ignore", invalid="ignore"):
            theta, info = stochastic_gradient_descent(
                grad_ridge, X, y, lam, np.zeros(degree), OPTIMIZERS[name](eta),
                run_epochs, batch, schedule=schedule, seed=seed,
                theta_ref=reference,
                callback=lambda th: float(cost_ridge(th, X, y, lam)) - reference_cost)
        seconds = time.perf_counter() - start
        history = info["history"]
        valid = not info["diverged"] and len(history) == run_epochs and np.all(np.isfinite(history))
        score = float(np.exp(np.mean(np.log(np.maximum(history[-200:], 1e-300))))) if valid else None
        prediction = scaler.y_mean + Xt @ theta
        return {"theta": theta, "history": history, "valid": valid, "score": score,
                "final_relative_error": float(info["errors"][-1]) if valid else None,
                "excess_cost": float(history[-1]) if valid else None,
                "test_mse": float(np.mean((prediction - y_test) ** 2)) if valid else None,
                "prediction_rmse_to_reference": float(np.sqrt(np.mean((prediction-reference_prediction) ** 2))) if valid else None,
                "time_s": seconds, "updates": info["updates"]}

    def summarize(name, eta, batch, decay=False):
        """LLM-assisted: generated by OpenAI Codex on 5 October 2026
        for the supplemental experiments described in the module docstring.
        """
        runs = [run(name, eta, batch, seed, decay) for seed in (0, 1, 2)]
        assert all(row["valid"] for row in runs), (name, eta, batch, decay)
        med = np.median([row["history"] for row in runs], axis=0)
        return {"eta0": float(eta), "decay_t1_epochs": 250 if decay else None,
                "updates_per_epoch": int(np.ceil(len(y)/batch)),
                "total_updates": runs[0]["updates"],
                "sample_gradient_evaluations": epochs * len(y),
                "median_excess_cost_checkpoints": {str(k):float(med[k-1]) for k in (1, 10, 100, 500, 1000, 2000)},
                **{f"median_{key}":float(np.median([row[key] for row in runs]))
                   for key in ("final_relative_error", "excess_cost", "test_mse", "prediction_rmse_to_reference", "time_s")}}

    # Each optimizer is tuned on the same 9-point grid; tuning uses training costs only.
    eta_grid = np.logspace(-4, 0, 9)
    out["ridge_sgd_methods_M10"] = {}
    for name in OPTIMIZERS:
        scan = [run(name, eta, 10, 0) for eta in eta_grid]
        best = min((i for i in range(len(scan)) if scan[i]["valid"]), key=lambda i:scan[i]["score"])
        out["ridge_sgd_methods_M10"][name] = {
            "eta_grid": eta_grid.tolist(), "tail_cost_scores": [r["score"] for r in scan],
            "constant": summarize(name, eta_grid[best], 10),
            "decaying_same_initial_eta": summarize(name, eta_grid[best], 10, decay=True)}

    # Batch-size comparison uses a common 7-point GD grid and the same decay schedule.
    batch_grid = np.logspace(-3, np.log10(0.25), 7)
    out["ridge_sgd_batch_size"] = {}
    for batch in (5, 20, 80):
        scan = [run("gd", eta, batch, 0) for eta in batch_grid]
        best = min((i for i in range(len(scan)) if scan[i]["valid"]), key=lambda i:scan[i]["score"])
        out["ridge_sgd_batch_size"][str(batch)] = {
            "eta_grid": batch_grid.tolist(), "tail_cost_scores": [r["score"] for r in scan],
            "constant": summarize("gd", batch_grid[best], batch),
            "decaying_same_initial_eta": summarize("gd", batch_grid[best], batch, decay=True)}
    out["ridge_full_batch_gd_eta_opt"] = summarize("gd", eta_opt, len(y))

    # Full-batch SGD must reproduce the same Ridge GD iterates (up to rounding).
    gd_theta, _ = gradient_descent(make_gradient("ridge", X, y, lam), np.zeros(degree),
                                   GD(0.1), 500)
    sgd_theta = run("gd", 0.1, len(y), 0, run_epochs=500)["theta"]
    out["ridge_full_batch_sgd_vs_gd_max_abs"] = float(np.max(np.abs(gd_theta - sgd_theta)))
    assert np.allclose(gd_theta, sgd_theta, rtol=0, atol=1e-11)
    output = Path(__file__).resolve().parents[1] / "results" / "verification_supplement.json"
    output.write_text(json.dumps(out, indent=2, allow_nan=False) + "\n", encoding="utf-8")
    print(output)
    print(json.dumps(out["ridge_gradient_sources"], indent=2))
    for name, data in out["ridge_sgd_methods_M10"].items():
        row = data["constant"]
        print(name, "eta", row["eta0"], "relative error", row["median_final_relative_error"],
              "excess cost", row["median_excess_cost"], "seconds", row["median_time_s"])


if __name__ == "__main__":
    main()
