"""Tests of the closed-form regression code against Scikit-Learn and known properties.

LLM-assisted (code level 4): generated with Claude (Anthropic, Claude Code), October 2026; the
three tests marked below were generated by OpenAI Codex.

Codex correction, 5 October 2026: set the sklearn OLS reference cutoff to
1e-15 so dense least squares matches the custom pseudoinverse convention.
"""

import numpy as np
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from regression import (PolynomialRegression, Scaler, lasso_sklearn_parameters, make_data, mse,
                        polynomial_features, r2, ridge_parameters, ridge_shrinkage_factors)

x, y = make_data(60, noise=0.1, seed=1)
x_new = np.linspace(-0.95, 0.95, 25)


def test_metrics_match_sklearn():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    y_pred = y + 0.05 * np.sin(7 * x)
    assert np.isclose(mse(y, y_pred), mean_squared_error(y, y_pred))
    assert np.isclose(r2(y, y_pred), r2_score(y, y_pred))


def test_ols_matches_sklearn_linear_regression():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    ours = PolynomialRegression(degree=6, method="ols").fit(x, y)
    ref = make_pipeline(PolynomialFeatures(6, include_bias=False), LinearRegression(tol=1e-15))
    ref.fit(x[:, None], y)
    assert np.allclose(ours.predict(x_new), ref.predict(x_new[:, None]), atol=1e-8)


def test_ols_predictions_do_not_depend_on_scaling():
    # OLS with an (unpenalised) intercept is invariant under an affine change of the columns
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    scaled = PolynomialRegression(degree=6, method="ols", scale=True).fit(x, y)
    centred = PolynomialRegression(degree=6, method="ols", scale=False).fit(x, y)
    assert np.allclose(scaled.predict(x_new), centred.predict(x_new), atol=1e-8)


def test_high_degree_ols_matches_sklearn_with_explicit_svd_cutoff():
    """Codex, 5 October 2026: catch implicit dense-SVD truncation in sklearn.

    Degree 20 is full rank but ill-conditioned on this random design. In
    sklearn 1.9 the default tol=1e-6 retains only 16 directions; explicit
    tol=1e-15 must retain all 20, as our np.linalg.pinv implementation does.

    LLM-assisted: generated by OpenAI Codex on 5 October 2026 for the
    numerical-cutoff correction.
    """
    x_high, y_high = make_data(40, noise=0.1, seed=944)
    x_eval = np.linspace(-0.95, 0.95, 21)
    ours = PolynomialRegression(20).fit(x_high, y_high).predict(x_eval)
    ref = make_pipeline(PolynomialFeatures(20, include_bias=False), StandardScaler(),
                        LinearRegression(tol=1e-15)).fit(x_high[:, None], y_high)
    expected = ref.predict(x_eval[:, None])
    assert ref.named_steps["linearregression"].rank_ == 20
    # Different SVD implementations need a conditioning-aware tolerance.
    assert np.max(np.abs(ours - expected)) / (1 + np.max(np.abs(expected))) < 1e-7


def test_original_coefficients_reproduce_predictions():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    model = PolynomialRegression(degree=4, method="ols").fit(x, y)
    beta0, beta = model.scaler_.original_coefficients(model.theta_)
    direct = beta0 + polynomial_features(x_new, 4) @ beta
    assert np.allclose(direct, model.predict(x_new))


def test_ridge_matches_sklearn_with_alpha_n_lambda():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    lam = 1e-3
    X = polynomial_features(x, 8)
    sc = Scaler().fit(X, y)
    Xs, yc = sc.transform(X), sc.center(y)
    ours = ridge_parameters(Xs, yc, lam)
    ref = Ridge(alpha=len(y) * lam, fit_intercept=False).fit(Xs, yc).coef_
    assert np.allclose(ours, ref, atol=1e-10)
    # and the full pipeline (sklearn centres internally when fit_intercept=True)
    model = PolynomialRegression(degree=8, method="ridge", lam=lam).fit(x, y)
    pipe = make_pipeline(PolynomialFeatures(8, include_bias=False), StandardScaler(),
                         Ridge(alpha=len(y) * lam)).fit(x[:, None], y)
    assert np.allclose(model.predict(x_new), pipe.predict(x_new[:, None]), atol=1e-10)


def test_ridge_goes_to_ols_for_small_lambda():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    ols = PolynomialRegression(degree=5, method="ols").fit(x, y)
    ridge = PolynomialRegression(degree=5, method="ridge", lam=1e-14).fit(x, y)
    assert np.allclose(ols.theta_, ridge.theta_, atol=1e-6)


def test_shrinkage_factors_between_zero_and_one():
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    X = Scaler().fit(polynomial_features(x, 10), y).transform(polynomial_features(x, 10))
    f = ridge_shrinkage_factors(X, 1e-2)
    assert np.all((f > 0) & (f < 1)) and np.all(np.diff(f) <= 0)


def test_lasso_solution_satisfies_optimality_conditions():
    # subgradient condition for (1/n)||y - X theta||^2 + lam ||theta||_1
    """LLM-assisted: generated with Claude (Claude Code, October 2026)."""
    lam = 5e-3
    X = polynomial_features(x, 6)
    sc = Scaler().fit(X, y)
    Xs, yc = sc.transform(X), sc.center(y)
    theta = lasso_sklearn_parameters(Xs, yc, lam)
    corr = (2.0 / len(yc)) * Xs.T @ (yc - Xs @ theta)
    active = theta != 0
    assert np.allclose(corr[active], lam * np.sign(theta[active]), atol=1e-6)
    assert np.all(np.abs(corr[~active]) <= lam + 1e-6)


def test_checked_lasso_continues_failed_candidates_and_certifies_them():
    """A one-sweep first pass must not silently enter a model-selection grid.

    LLM-assisted: generated by Codex, 5 October 2026, to test the added
    convergence gate with a deliberately insufficient initial budget.
    """
    from regression import checked_lasso_path
    X = polynomial_features(x, 6)
    sc = Scaler().fit(X, y)
    Xs, yc = sc.transform(X), sc.center(y)
    theta, audit = checked_lasso_path(Xs, yc, [0.01, 0.001], max_iter=1)
    assert audit['refined'] == 2 and audit['unresolved'] == 0
    assert audit['max_dual_gap'] <= audit['dual_gap_tolerance']
    assert audit['max_kkt_residual'] <= audit['kkt_tolerance']
    for j, lam in enumerate((0.01, 0.001)):
        ref = lasso_sklearn_parameters(Xs, yc, lam)
        assert np.max(np.abs(Xs @ (theta[:, j] - ref))) < 1e-5


def test_checked_lasso_rejects_an_unresolved_candidate():
    """Both insufficient budgets must raise instead of reporting convergence.

    LLM-assisted: generated by Codex, 5 October 2026, for the convergence gate.
    """
    import pytest
    from regression import checked_lasso_path
    X = polynomial_features(x, 6)
    sc = Scaler().fit(X, y)
    with pytest.raises(RuntimeError, match='Unconverged Lasso'):
        checked_lasso_path(sc.transform(X), sc.center(y), [0.001],
                           max_iter=1, refinement_iter=1)
